AnimeWebSite/AnimeWebSite/Controllers/AdminController.cs
using AnimeWebSite.Contracts;
using AnimeWebSite.Services;
using AnimeWebSite.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AnimeWebSite.Controllers
{
    [Authorize(Policy ="Administrator")]
    public class AdminController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private readonly IFileSystemService _fIleSystem;

        public AdminController(IServiceManager serviceManager,
                               IFileSystemService fIleSystem)
        {
            _serviceManager = serviceManager;
            _fIleSystem = fIleSystem;
        }
        public IActionResult AddAnime()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddAnimeAsync(AddAnimeViewModel anime)
        {
            if (anime is null)
            {
                return View(anime);
            }
            anime.ImagePath = _fIleSystem.Create(anime.Image, FileSystemService.animeImages,null);

            await _serviceManager.AnimeService.CreateAsync(anime);

            return Redirect("/");
        }

        public IActionResult Admin()
        {
            return View();
        }
    }
}

AnimeWebSite/AnimeWebSite/Controllers/UserProfileController.cs
using AnimeWebSite.Contracts.User;
using AnimeWebSite.Identity.Domain.Entities.Users;
using AnimeWebSite.Services;
using AnimeWebSite.Services.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AnimeWebSite.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly IFileSystemService _fileSystem;
        private readonly ILogger<UserProfileController> _logger;

        public UserProfileController(UserManager<ApplicationUser> userManager,
                                     IMapper mapper,
                                     IFileSystemService fileSystem,
                                     ILogger<UserProfileController> logger)
        {
            _userManager = userManager;
            _mapper = mapper;
            _fileSystem = fileSystem;
            _logger = logger;
        }

        [HttpGet("[controller]/MyProfile")]
        public async Task<IActionResult> UserProfile()
        {
            var user = await _userManager.GetUserAsync(User);
            var userVM = _mapper.Map<UpdateUserViewModel>(user);
            return View(userVM);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateUser(UpdateUserViewModel userVM)
        {
            var t = await _userManager.GetUserAsync(User);
            var user = _mapper.Map(userVM, t);
            if(userVM.UploadedImage is not null)
            {
                var deleteResult = _fileSystem.DeleteFile(user.ImagePath);
                if (!deleteResult)
                {
                    _logger.LogError($"Can not delete user image-{user.ImagePath}");
                }
                user.ImagePath = _fileSystem.Create(userVM.UploadedImage, FileSystemService.userImages,t.Id);
            }

            var result = await _userManager.UpdateAsync(user);

            return RedirectToAction(nameof(UserProfile));

        }
    }
}

AnimeWebSite/AnimeWebSite/Views/Shared/_Layout.cshtml
@using AnimeWebSite.Identity.Domain.Entities.Users
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@inject UserManager<ApplicationUser> _userManager
@{
    ApplicationUser user = await _userManager.GetUserAsync(User); 
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnimeWebSite</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/css/plyr.css" type="text/css">
    <link rel="stylesheet" href="/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/css/style.css" type="text/css">
    <link href="~/Content/MvcDatalist/mvc-datalist.css" rel="stylesheet">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a asp-controller="Home" asp-action="Index">
                            <img src="/img/logo.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li><a asp-controller="Home" asp-action="Index">Homepage</a></li>
                                <li>
                                    <a href="./categories.html">Categories <span class="arrow_carrot-down"></span></a>
                                    <ul class="dropdown">
                                        <li><a asp-controller="Home" asp-action="Index">Categories</a></li>
                                        <li><a asp-controller="AnimeDetails" asp-action="Details">Anime Details</a></li>
                                        <li><a href="./anime-watching.html">Anime Watching</a></li>
                                        <li><a asp-controller="Admin" asp-action="Admin">Admin</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a asp-controller="UserProfile" asp-action="UserProfile"><span class="icon_profile"></span></a>
                                    <ul class="dropdown">
                                        @if (User.Identity.IsAuthenticated)
                                                                    {
                                            <li><a asp-controller="UserProfile" asp-action="MyProfile">My Profile</a></li>
                                            <li><a asp-controller="Authentication" asp-action="LogOut">Log Out</a></li>
                                        }
                                        else
                                        {
                                            <li><a asp-controller="Authentication" asp-action="SignUp">Sign Up</a></li>
                                            <li><a asp-controller="Authentication" asp-action="SignIn">Sign In</a></li>
                                        }
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="#" class="search-switch"><span class="icon_search"></span></a>
                        @if (User.Identity.IsAuthenticated && user != null)
                        {
                            <span style="color:burlywood">Hello,@user.UserName</span>
                        }
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="./index.html"><img src="img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="./index.html">Homepage</a></li>
                            <li><a href="./categories.html">Categories</a></li>
                            <li><a href="./blog.html">Our Blog</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>

                </div>
            </div>
        </div>
    </footer>
    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->
    <!-- Js Plugins -->
    <script src="/js/jquery-3.3.1.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/player.js"></script>
    <script src="/js/jquery.nice-select.min.js"></script>
    <script src="/js/mixitup.min.js"></script>
    <script src="/js/jquery.slicknav.js"></script>
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>