AnimeWebSite/AnimeWebSite/Controllers/AnimeController.cs
using AnimeWebSite.Domain.Entities;
using AnimeWebSite.Identity.Domain.Entities.Users;
using AnimeWebSite.Services.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AnimeWebSite.Controllers
{
    public class AnimeController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public AnimeController(IServiceManager serviceManager, UserManager<ApplicationUser> userManager,
                               IMapper mapper)
        {
            _serviceManager = serviceManager;
            _userManager = userManager;
            _mapper = mapper;
        }

        [HttpGet("[controller]/{id}")]
        public async Task<IActionResult> Details(int id)
        {

            var anime = await _serviceManager.AnimeService.GetByIdWithReviewsAsync(id);
            if (anime is null)
            {
                return NotFound(anime);
            }

            return View(anime);
        }

        [HttpGet("[controller]/Watching/{id}")]
        public async Task<IActionResult> Watching(int id)
        {
            var anime = await _serviceManager.AnimeService.GetByIdWithCommentsAsync(id);
            if (anime is null)
            {
                return NotFound(anime);
            }

            return View(anime);
        }

        [Authorize]
        [HttpPost("[controller]/make-comment")]
        public async Task<IActionResult> Comment(int animeId, string comment)
        {
            var user = await _userManager.GetUserAsync(User);

            await _serviceManager.CommentsService.CreateAsync(animeId, user.Id,comment);

            return Ok();
        }


        [Authorize]
        public async void Review(int animeId, string review)
        {
            var user = await _userManager.GetUserAsync(User);

            await _serviceManager.ReviewsService.CreateAsync(animeId, user.Id, review);

        }
    }
}

AnimeWebSite/AnimeWebSite/Views/Anime/Details.cshtml
@using AnimeWebSite.Domain.Entities
@model Anime
<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                    <a href="./categories.html">Categories</a>
                    <span>Romance</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Anime Section Begin -->
<section class="anime-details spad">
    <div class="container">
        <div class="anime__details__content">
            <div class="row">
                <div class="col-lg-3">
                    <div class="anime__details__pic set-bg" data-setbg="@Url.Content(Model.ImagePath)">
                        <div class="comment"><i class="fa fa-comments"></i> 11</div>
                        <div class="view"><i class="fa fa-eye"></i> 9141</div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="anime__details__text">
                        <div class="anime__details__title">
                            <h3>@Model.Name</h3>
                            <span>@Model.OriginalName</span>
                        </div>
                        <div class="anime__details__rating">
                            <div class="rating">
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star-half-o"></i></a>
                            </div>
                            <span>1.029 Votes</span>
                        </div>
                        <p>@Model.Description</p>
                        <div class="anime__details__widget">
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <ul>
                                        <li><span>Type:</span> TV Series</li>
                                        <li><span>Studios:</span> Lerche</li>
                                        <li><span>Date aired:</span> @Model.ReleaseDate</li>
                                        <li><span>Status:</span> Airing</li>
                                        <li><span>Genre:</span> @Model.Genres</li>
                                        <li><span>Views:</span> 131,541</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="anime__details__btn">
                                <a href="#" class="follow-btn"><i class="fa fa-heart-o"></i> Follow</a>
                                <a asp-controller="Anime" asp-action="Watching" asp-route-id="@Model.Id" class="watch-btn"><span>Watch Now</span> <i class="fa fa-angle-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <div class="anime__details__review">
                        <div class="anime__details__form mb-5">
                            <div class="section-title">
                                <h5>Your Review</h5>
                            </div>
                            <form asp-action="Review">
                                <input type="hidden" name="id" value="@Model.Id" />
                                <textarea name="review" placeholder="Your Review"></textarea>
                                <button type="submit"><i class="fa fa-location-arrow"></i> Review</button>
                            </form>
                        </div>
                        <div class="section-title mb-3">
                            <h5>Reviews</h5>
                        </div>
                        @if (Model.Reviews is not null)
                        {
                            foreach (var item in Model.Reviews)
                            {
                                <div class="anime__review__item">
                                    <div class="anime__review__item__pic">
                                        <img src="@item.User.ImagePath">
                                    </div>
                                    <div class="anime__review__item__text">
                                        <h6>@item.User.UserName - <span>@item.PostedOn</span></h6>
                                        <p>
                                            @item.Content
                                        </p>
                                    </div>
                                </div>
                            }
                        }
                       
                    </div>

                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="anime__details__sidebar">
                        <div class="section-title">
                            <h5>you might like...</h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-1.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">Boruto: Naruto next generations</a></h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-2.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">The Seven Deadly Sins: Wrath of the Gods</a></h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-3.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">Sword art online alicization war of underworld</a></h5>
                        </div>
                        <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-4.jpg">
                            <div class="ep">18 / ?</div>
                            <div class="view"><i class="fa fa-eye"></i> 9141</div>
                            <h5><a href="#">Fate/stay night: Heaven's Feel I. presage flower</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- Anime Section End -->

AnimeWebSite/AnimeWebSite/Views/Anime/Watching.cshtml
@using AnimeWebSite.Domain.Entities
@model Anime

<!-- Anime Section Begin -->
<section class="anime-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="anime__video__player">
                    <video id="player" playsinline controls data-poster="./videos/anime-watch.jpg">
                        <source src="videos/1.mp4" type="video/mp4" />
                        <!-- Captions are optional -->
                        <track kind="captions" label="English captions" src="#" srclang="en" default />
                    </video>
                </div>
                <div class="anime__details__episodes">
                    <div class="section-title">
                        <h5>List Name</h5>
                    </div>
                    <a href="#">Ep 01</a>
                    <a href="#">Ep 02</a>
                    <a href="#">Ep 03</a>
                    <a href="#">Ep 04</a>
                    <a href="#">Ep 05</a>
                    <a href="#">Ep 06</a>
                    <a href="#">Ep 07</a>
                    <a href="#">Ep 08</a>
                    <a href="#">Ep 09</a>
                    <a href="#">Ep 10</a>
                    <a href="#">Ep 11</a>
                    <a href="#">Ep 12</a>
                    <a href="#">Ep 13</a>
                    <a href="#">Ep 14</a>
                    <a href="#">Ep 15</a>
                    <a href="#">Ep 16</a>
                    <a href="#">Ep 17</a>
                    <a href="#">Ep 18</a>
                    <a href="#">Ep 19</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="anime__details__form mb-4">
                    <div class="section-title">
                        <h5>Your Comment</h5>
                    </div>
                    <form asp-action="Comment">
                        <input type="hidden" name="id" value="@Model.Id" />
                        <textarea name="comment" placeholder="Your Comment"></textarea>
                        <button type="submit"><i class="fa fa-location-arrow"></i> Review</button>
                    </form>
                </div>
                <div class="anime__details__review">
                    <div class="section-title">
                        <h5>Reviews</h5>
                    </div>
                    @if (Model.Comments is not null)
                    {
                        foreach (var item in Model.Comments)
                        {
                            <div class="anime__review__item">
                                <div class="anime__review__item__pic">
                                    <img src="@item.User.ImagePath">
                                </div>
                                <div class="anime__review__item__text">
                                    <h6>@item.User.UserName - <span>@item.PostedOn</span></h6>
                                    <p>
                                        @item.Content
                                    </p>
                                </div>
                            </div>
                        }
                    }
                </div>

            </div>
        </div>
    </div>
</section>
<!-- Anime Section End -->